### ISSUE TITLE
Can't get project to build

### ISSUE THREAD

**Issue by brunobergher** [Khan/OhaiPrototope#18]
I'm just getting started with iOS development, so it might be my fault, but even using XCode 6.3 Beta, I can't get the project to build, as I get a few errors. The originating one is:

Layer.swift:633: `Initializer does not override a designated initializer from its superclass`

Do I need to install an additional package or something else I'm missing?

Thanks!

**Comment by andymatuschak** [comment]
Very sorry about that: the new version of Xcode yesterday changed some things around. Fixed in 8b4072f.
